[package]
name = "cdnup"
version = "0.1.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.0-beta.3"
env_logger = "0.7"
sqlx = { version = "0.4.0-beta.1", default-features = false, features = ["runtime-actix", "postgres"] }
actix-service = "1.0"
futures = "0.3"
hyper = "0.13"
hyper-tls = { version = "0.4", features = ["vendored"] }
lazy_static = "1.4"
tokio = "0.2"
tokio-tls = "0.3"
uuid = { version = "0.8", features = ["v4"] }
